### ISSUE TITLE
NanoSV on synthetic bam files

### ISSUE THREAD

**Issue by AlbertoMagi** [mroosmalen/nanosv#24]
I tried to use NanoSV on different bam files (obtained with last, BWA, minimap2 and ngmlr) and I always obtain the same error:

Traceback (most recent call last):
  File "/home/Workspace/Tools/Lib/Anaconda2/envs/albacore/bin/NanoSV", line 6, in <module>
    sys.exit(nanosv.NanoSV.main())
  File "/home/Workspace/Tools/Lib/Anaconda2/envs/albacore/lib/python3.6/site-packages/nanosv/NanoSV.py", line 52, in main
    utils.parse_bam.parse_bam()
  File "/home/Workspace/Tools/Lib/Anaconda2/envs/albacore/lib/python3.6/site-packages/nanosv/utils/../utils/parse_bam.py", line 46, in parse_bam
    read = r.Read(line.query_name, line.infer_read_length())
AttributeError: 'pysam.calignedsegment.AlignedSegment' object has no attribute 'infer_read_length'

Reads where obtained by using PBSim.
Bam file works properly with both Sniffles and Lumpy.
Any suggestions??

Tank You 

Alberto

**Comment by jaesvi** [comment]
Hi Alberto,
Could you please check your version of Pysam? 
You can do this In any interactive python session with
```
import pysam
pysam.__version__
```
The method  'infer_read_length' was introduced in release 0.11.0, so if it shows anything lower than that, updating will probably solve the issue. 
Best,
Jose

**Comment by njaupan** [comment]
Dear Jaesvi,

I have meet similar problem, bam files which obtained from LAST  works properly on Sniffles.

Traceback (most recent call last):
  File "/home/sophie/env/bin/NanoSV", line 11, in <module>
    sys.exit(main())
  File "/home/sophie/env/lib/python3.5/site-packages/nanosv/NanoSV.py", line 50, in main
    utils.coverage.calculate_coverage_bed()
  File "/home/sophie/env/lib/python3.5/site-packages/nanosv/utils/../utils/coverage.py", line 18, in calculate_coverage_bed
    cmd = NanoSV.opts_sambamba + " depth base --min-coverage=0 " + NanoSV.opts_bam + " -L " + NanoSV.opts_bed + " --nthreads=" + NanoSV.opts_threads + " 2> /dev/null | awk '{if (NR!=1) print $3}'"
TypeError: Can't convert 'int' object to str implicitly

Pysam version is newest
/home/sophie/env/lib/python3.5/site-packages (0.14.1)

Do  you have any suggestion?

Thank you 
Ivy
